### ISSUE TITLE
Contributions

### ISSUE THREAD

**Issue by Sephster** [OSCELOT/LoginAs#1]
Hello. I was wondering what is the best way to contribute to this project? I noticed that the repository is only distributing the war file. What is the best way to get access to the source code? I was thinking it might be best to just open the war file but wanted to check in case there were any concerns with this. Many thanks and thanks for your effort with this repository

**Comment by markoneil** [comment]
This project is managed by All The Ducks and they prefer to keep the source in their git repo. Please reach out to wiley Fuller <wiley@alltheducks.com> - he can help.

Cheers,
-m

**Comment by wileyfuller** [comment]
This project, to the best of my knowledge/memory, is not one of mine. @markoneil , perhaps you're thinking of the Autosignon auth provider?

**Comment by Sephster** [comment]
Does @smachaje perhaps know where the source is? Thanks for your help guys. Appreciated

**Comment by moneil** [comment]
I just added a SRC war file to the Git repo.

Cheers,
-m

Mark O'Neil
Director, Product Management, Platform and APIs
Blackboard Inc.

Quick Links:
Developer AMI<https://aws.amazon.com/marketplace/seller-profile?id=f6f7de05-e6d2-47f8-96e8-51cc4b38182b>
Developer Program<https://developer.blackboard.com/>
Developer Community<https://community.blackboard.com/community/developers>

**Comment by markoneil** [comment]
Yes, that is exactly what happened.

I dug up the original LoginAs src and doc archives and added them to the git repo.

Thank you Wiley!

Cheers,
-m

**Comment by Sephster** [comment]
Thanks @markoneil - is there an active developer for this project at the moment or is it provided as is? There are some adjustments I was hoping to make or propose and was just wondering the best way to approach this. Thanks for your help to date.

**Comment by markoneil** [comment]
I believe it safe to assume this is an 'as is' project. Please feel free to adopt/fork the project or to issue pull requests against this version.

You might consider contacting @smachaje to see how active he is on the project.

**Comment by Sephster** [comment]
Thanks Mark. This is good to know. I will likely submit a few PRs in the coming months. Many thanks for your help.
